/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1cp2upload;
import com.mycompany.oopca1cp2upload.FoodTracker;

/**
 *
 * @author taraj
 */
public class FoodGUI extends javax.swing.JFrame {
    private String userName;
    private int userAge;
    private double userWeight;
    FoodTracker foodTracker = new FoodTracker();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FoodGUI.class.getName());
    String mealDesc = "";
    int mealCal= 0;
    private int dailyWaterIntake;
    private  SleepAnalyzer sleepAnalyzer;
    private String moodRating;
    private String calories;
    /**
     * Creates new form FoodGUI
     */
    public FoodGUI(String userName, int userAge, double userWeight, int dailyWaterIntake,SleepAnalyzer sleep,String moodRating) {
        initComponents();
        this.userName = userName;
        this.userAge = userAge;
        this.userWeight = userWeight;
        this.dailyWaterIntake = dailyWaterIntake;
        this.sleepAnalyzer = sleep;
        this.moodRating = moodRating;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mealCalInputGUI = new javax.swing.JTextField();
        mealInputGUI = new javax.swing.JTextField();
        AddMealSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SaveOneMeal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Food Tracker");

        jLabel2.setText("Please enter a meal you have eaten today:");

        jLabel3.setText("Please enter the amount of calories:");

        mealCalInputGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealCalInputGUIActionPerformed(evt);
            }
        });

        mealInputGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealInputGUIActionPerformed(evt);
            }
        });

        AddMealSave.setText("Yes");
        AddMealSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMealSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Would you like to enter another meal?");

        SaveOneMeal.setText("No");
        SaveOneMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveOneMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(AddMealSave)
                .addGap(18, 18, 18)
                .addComponent(SaveOneMeal)
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mealInputGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealCalInputGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealInputGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mealCalInputGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMealSave)
                    .addComponent(jLabel4)
                    .addComponent(SaveOneMeal))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMealSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMealSaveActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new FoodGUI(userName, userAge, userWeight, dailyWaterIntake,sleepAnalyzer,moodRating).setVisible(true);

            }
        });
        dispose();
        //add code to save to var/file
    }//GEN-LAST:event_AddMealSaveActionPerformed

    private void SaveOneMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveOneMealActionPerformed
        
        java.awt.EventQueue.invokeLater(() -> {
           calories = mealCalInputGUI.getText();
           String mealDesc = mealInputGUI.getText();
           
            Forum forum = new Forum();
            ForumGUI gui = new ForumGUI(userName, userAge, userWeight, dailyWaterIntake, forum,sleepAnalyzer,moodRating,calories,mealDesc);
            gui.setVisible(true);
        });
        dispose();
        Meals newMeal = new Meals(mealDesc, mealCal);
        foodTracker.AddMeal(newMeal);
    }//GEN-LAST:event_SaveOneMealActionPerformed

    private void mealInputGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealInputGUIActionPerformed
        String mealDesc = mealInputGUI.getText();
        
      
    }//GEN-LAST:event_mealInputGUIActionPerformed

    private void mealCalInputGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealCalInputGUIActionPerformed
        int mealCal = Integer.parseInt(mealCalInputGUI.getText());
    }//GEN-LAST:event_mealCalInputGUIActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMealSave;
    private javax.swing.JButton SaveOneMeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mealCalInputGUI;
    private javax.swing.JTextField mealInputGUI;
    // End of variables declaration//GEN-END:variables
}
