/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1cp2upload;

/**
 *
 * @author lapi
 */
public class ForumGUI extends javax.swing.JFrame {

    private String userName;
    private int userAge;
    private double userWeight;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForumGUI.class.getName());
    private final Forum forum;
    private int dailyWaterIntake;
    private int waterRemaining;
    private  SleepAnalyzer sleepAnalyzer;
   private String moodRating;
   private String calories;
   private String mealDesc;


    /**
     * Creates new form Forum
     */
    public ForumGUI(String userName, int userAge, double userWeight, int dailyWaterIntake, Forum forum,SleepAnalyzer sleep,String moodRating,String calories,String mealDesc) {
        initComponents();
        this.userName = userName;
        this.userAge = userAge;
        this.userWeight = userWeight;
        this.forum = forum;
        this.dailyWaterIntake = dailyWaterIntake;
        this.sleepAnalyzer = sleep;
        this.moodRating = moodRating;
        this.calories = calories;
        this.mealDesc = mealDesc;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertForumText = new javax.swing.JTextField();
        addPostButton = new javax.swing.JButton();
        showPostButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showForumText = new javax.swing.JTextArea();
        doneForumButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insertForumText.setText("Insert Text");
        insertForumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertForumTextActionPerformed(evt);
            }
        });

        addPostButton.setText("Add Post");
        addPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPostButtonActionPerformed(evt);
            }
        });

        showPostButton.setText("Show Posts");
        showPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPostButtonActionPerformed(evt);
            }
        });

        showForumText.setColumns(20);
        showForumText.setRows(5);
        jScrollPane1.setViewportView(showForumText);

        doneForumButton.setText("Done");
        doneForumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneForumButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Forum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertForumText)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 193, Short.MAX_VALUE)
                                .addComponent(showPostButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addPostButton))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(doneForumButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertForumText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPostButton)
                    .addComponent(showPostButton))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(doneForumButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPostButtonActionPerformed
        String text = insertForumText.getText().trim();
        forum.addPost(text);
        insertForumText.setText("");
    }//GEN-LAST:event_addPostButtonActionPerformed

    private void showPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPostButtonActionPerformed
        showForumText.setText("");

        for (String p : forum.getPosts()) {
            showForumText.append(p + "\n");
        }
    }//GEN-LAST:event_showPostButtonActionPerformed

    private void insertForumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertForumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertForumTextActionPerformed

    private void doneForumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneForumButtonActionPerformed
        HydrationTracker hydrationTracker = new HydrationTracker();
        hydrationTracker.setDailyWaterIntake(dailyWaterIntake);
        int waterRemaining = hydrationTracker.compareWater();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DashboardGUI(userName, userAge, userWeight, dailyWaterIntake,waterRemaining,sleepAnalyzer,moodRating,calories,mealDesc).setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_doneForumButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPostButton;
    private javax.swing.JButton doneForumButton;
    private javax.swing.JTextField insertForumText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea showForumText;
    private javax.swing.JButton showPostButton;
    // End of variables declaration//GEN-END:variables
}
