/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1cp2upload;

/**
 *
 * @author taraj
 */
public class HydrationGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HydrationGUI.class.getName());
    private String userName;
    private int userAge;
    private double userWeight;
    int dailyWaterIntake;
    private SleepAnalyzer sleepAnalyzer;
    /**
     * Creates new form HydrationGUI
     */
    public HydrationGUI(String userName, int userAge, double userWeight,SleepAnalyzer sleep) {
        initComponents();
        this.userName = userName;
        this.userAge = userAge;
        this.userWeight = userWeight;
        this.dailyWaterIntake = dailyWaterIntake;
        this.sleepAnalyzer = sleep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hydTrackerText = new javax.swing.JLabel();
        waterQuestionGUI = new javax.swing.JLabel();
        waterGUIInput = new javax.swing.JTextField();
        hydSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hydTrackerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hydTrackerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hydTrackerText.setText("Hydration Tracker");

        waterQuestionGUI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waterQuestionGUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterQuestionGUI.setText("Please enter the amount of water you have drank today (ml): ");
        waterQuestionGUI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        waterGUIInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterGUIInputActionPerformed(evt);
            }
        });

        hydSubmit.setText("Submit");
        hydSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hydSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(waterQuestionGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(waterGUIInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(hydSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(hydTrackerText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hydTrackerText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waterQuestionGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(waterGUIInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(hydSubmit)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    validWater = false;
        while (!validWater) {
            String waterInput = input.nextLine();
            try {
                dailyWaterIntake = Integer.parseInt(waterInput);
                if (dailyWaterIntake > 0) {
                    validWater = true;
                    hydrationTracker.setDailyWaterIntake(dailyWaterIntake);
                } else {
                    System.out.println("Please enter an integer greater than 1");
                }
                //catch when int conversion doesnt work
            } catch (NumberFormatException waterException) {
                System.out.println("Please enter a valid number");
            }
        }
    */
    private void waterGUIInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterGUIInputActionPerformed
        int dailyWaterIntake = Integer.parseInt(waterGUIInput.getText());
        
    }//GEN-LAST:event_waterGUIInputActionPerformed

    private void hydSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hydSubmitActionPerformed
        int dailyWaterIntake = Integer.parseInt(waterGUIInput.getText());
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new MoodGUI(userName, userAge, userWeight, dailyWaterIntake,sleepAnalyzer).setVisible(true);

            }
        });
        dispose();
    }//GEN-LAST:event_hydSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hydSubmit;
    private javax.swing.JLabel hydTrackerText;
    private javax.swing.JTextField waterGUIInput;
    private javax.swing.JLabel waterQuestionGUI;
    // End of variables declaration//GEN-END:variables
}
