/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1cp2upload;

/**
 *
 * @author taraj
 */
public class DashboardGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardGUI.class.getName());
    private String userName;
    private int userAge;
    private double userWeight;
    private int dailyWaterIntake;
    private int waterRemaining;
    private  SleepAnalyzer sleepAnalyzer;
    private String moodRating;
     private String calories;
     private String mealDesc;

    HydrationTracker hydrationTracker = new HydrationTracker();

    /**
     * Creates new form DashboardGUI
     */
    public DashboardGUI(String userName, int userAge, double userWeight, int dailyWaterIntake, int waterRemaining,SleepAnalyzer sleep,String moodRating,String calories,String mealDesc) {
        
        initComponents();
        this.userName = userName;
        this.userAge = userAge;
        this.userWeight = userWeight;
        this.dailyWaterIntake = dailyWaterIntake;
        this.waterRemaining = waterRemaining;
        this.sleepAnalyzer = sleep;
        this.moodRating = moodRating;
        this.calories = calories;
        this.mealDesc= mealDesc;

        nameGUIOutput.setText(userName);
        ageGUIOutput.setText(Integer.toString(userAge));
        weightGUIOutput.setText(Double.toString(userWeight) + " kg");
        WaterGUIOutput.setText(Integer.toString(dailyWaterIntake) + " ml");
        waterRemainingGUIOutput.setText(Integer.toString(waterRemaining) + " ml");
        averageWaterGUIOutput.setText(sleepAnalyzer.getAverageSleep() + " Hours");
        moodGUIOutput.setText(moodRating+ " /10");
        caloriesGUIOutput.setText(calories);
        mealsGUIOutput.setText(mealDesc);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardTitle = new javax.swing.JLabel();
        dashboardUserGUIText = new javax.swing.JLabel();
        dashboardMoodGUIText = new javax.swing.JLabel();
        dashboardWaterGUIText = new javax.swing.JLabel();
        dashboardWaterLeftGUIText = new javax.swing.JLabel();
        dashboardAverageSleepGUIText = new javax.swing.JLabel();
        dashboardMealsGUIText = new javax.swing.JLabel();
        dashboardCaloriesGUIText = new javax.swing.JLabel();
        WaterGUIOutput = new javax.swing.JLabel();
        nameGUIOutput = new javax.swing.JLabel();
        ageGUIOutput = new javax.swing.JLabel();
        weightGUIOutput = new javax.swing.JLabel();
        mealsGUIOutput = new javax.swing.JLabel();
        waterRemainingGUIOutput = new javax.swing.JLabel();
        caloriesGUIOutput = new javax.swing.JLabel();
        averageWaterGUIOutput = new javax.swing.JLabel();
        moodGUIOutput = new javax.swing.JLabel();
        dashboardUserGUIText1 = new javax.swing.JLabel();
        dashboardUserGUIText2 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));

        dashboardTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitle.setText("Dashboard");

        dashboardUserGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardUserGUIText.setText("User name:");

        dashboardMoodGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardMoodGUIText.setText("Mood:");

        dashboardWaterGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardWaterGUIText.setText("Water drank:");

        dashboardWaterLeftGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardWaterLeftGUIText.setText("Water remaining:");

        dashboardAverageSleepGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardAverageSleepGUIText.setText("Average sleep:");

        dashboardMealsGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardMealsGUIText.setText("Meals:");

        dashboardCaloriesGUIText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardCaloriesGUIText.setText("Calories:");

        WaterGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ageGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        weightGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mealsGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        waterRemainingGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        caloriesGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        averageWaterGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        moodGUIOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dashboardUserGUIText1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardUserGUIText1.setText("Weight:");

        dashboardUserGUIText2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardUserGUIText2.setText("Age:");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(dashboardTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dashboardCaloriesGUIText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dashboardMealsGUIText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(WaterGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dashboardMoodGUIText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(moodGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(mealsGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(caloriesGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dashboardAverageSleepGUIText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(averageWaterGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dashboardWaterLeftGUIText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dashboardWaterGUIText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(waterRemainingGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dashboardUserGUIText1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(weightGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dashboardUserGUIText2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ageGUIOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dashboardUserGUIText, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 330, Short.MAX_VALUE)))
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashboardTitle)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardUserGUIText)
                            .addComponent(nameGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ageGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dashboardUserGUIText2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weightGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardWaterGUIText)
                            .addComponent(WaterGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moodGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardMoodGUIText, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(waterRemainingGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardWaterLeftGUIText))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dashboardMealsGUIText)
                            .addComponent(mealsGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardCaloriesGUIText)
                            .addComponent(caloriesGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dashboardAverageSleepGUIText)
                                    .addComponent(averageWaterGUIOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dashboardUserGUIText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(SaveButton)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        
        MyFile file = new MyFile (".output.txt");
        String [] strings = {
        "Username:", userName,"Age:",String.valueOf(userAge),"Weight:",String.valueOf(userWeight),"Meal:",mealDesc,"Calories:",calories,"Mood:",moodRating,"Water remaining(ml):",String.valueOf(dailyWaterIntake),"Average hours slept:",String.valueOf(sleepAnalyzer.getAverageSleep())
        };
        file.rewriteFile(strings);
        dispose();
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel WaterGUIOutput;
    private javax.swing.JLabel ageGUIOutput;
    private javax.swing.JLabel averageWaterGUIOutput;
    private javax.swing.JLabel caloriesGUIOutput;
    private javax.swing.JLabel dashboardAverageSleepGUIText;
    private javax.swing.JLabel dashboardCaloriesGUIText;
    private javax.swing.JLabel dashboardMealsGUIText;
    private javax.swing.JLabel dashboardMoodGUIText;
    private javax.swing.JLabel dashboardTitle;
    private javax.swing.JLabel dashboardUserGUIText;
    private javax.swing.JLabel dashboardUserGUIText1;
    private javax.swing.JLabel dashboardUserGUIText2;
    private javax.swing.JLabel dashboardWaterGUIText;
    private javax.swing.JLabel dashboardWaterLeftGUIText;
    private javax.swing.JLabel mealsGUIOutput;
    private javax.swing.JLabel moodGUIOutput;
    private javax.swing.JLabel nameGUIOutput;
    private javax.swing.JLabel waterRemainingGUIOutput;
    private javax.swing.JLabel weightGUIOutput;
    // End of variables declaration//GEN-END:variables
}
