/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopca1cp2upload;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author taraj and ryanwhite
 */
public class SleepGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SleepGUI.class.getName());
    private String userName;
    private int userAge;
    private double userWeight;

    /**
     * Creates new form SleepGUI
     */
    public SleepGUI(String userName, int userAge, double userWeight) {
        initComponents();
        this.userName = userName;
        this.userAge = userAge;
        this.userWeight = userWeight;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        sleepPageText = new javax.swing.JLabel();
        sleepInfoText = new javax.swing.JLabel();
        tuesdayLabel = new javax.swing.JLabel();
        wednesdayLabel = new javax.swing.JLabel();
        thursdayLabel = new javax.swing.JLabel();
        fridayLabel = new javax.swing.JLabel();
        mondayLabel = new javax.swing.JLabel();
        saturdayLabel = new javax.swing.JLabel();
        sundayLabel = new javax.swing.JLabel();
        mondayInput = new javax.swing.JTextField();
        tuesdayInput = new javax.swing.JTextField();
        wednesdayInput = new javax.swing.JTextField();
        fridayInput = new javax.swing.JTextField();
        thursdayInput = new javax.swing.JTextField();
        sundayInput = new javax.swing.JTextField();
        saturdayInput = new javax.swing.JTextField();
        sleepSubmit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sleepPageText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sleepPageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sleepPageText.setText("Sleep Data:");

        sleepInfoText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sleepInfoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sleepInfoText.setText("Please enter the amount of hours you slept each night:");

        tuesdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tuesdayLabel.setText("Tuesday");

        wednesdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wednesdayLabel.setText("Wednesday");

        thursdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thursdayLabel.setText("Thursday");

        fridayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fridayLabel.setText("Friday");

        mondayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mondayLabel.setText("Monday");

        saturdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saturdayLabel.setText("Saturday");

        sundayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sundayLabel.setText("Sunday");

        mondayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayInputActionPerformed(evt);
            }
        });

        tuesdayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayInputActionPerformed(evt);
            }
        });

        wednesdayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayInputActionPerformed(evt);
            }
        });

        fridayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayInputActionPerformed(evt);
            }
        });

        thursdayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayInputActionPerformed(evt);
            }
        });

        sundayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayInputActionPerformed(evt);
            }
        });

        saturdayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayInputActionPerformed(evt);
            }
        });

        sleepSubmit.setText("Submit");
        sleepSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepSubmitActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter the book you read before bed");

        jCheckBox1.setText("Read before bed?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Do you get up during the night?");

        jTextField2.setText("Enter why?");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(sleepSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(sleepPageText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(sleepInfoText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sundayLabel)
                    .addComponent(saturdayLabel)
                    .addComponent(thursdayLabel)
                    .addComponent(fridayLabel)
                    .addComponent(wednesdayLabel)
                    .addComponent(tuesdayLabel)
                    .addComponent(mondayLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tuesdayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(mondayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(wednesdayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(fridayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(thursdayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(saturdayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(sundayInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(sleepPageText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sleepInfoText)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mondayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tuesdayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(wednesdayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(thursdayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fridayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(saturdayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sundayLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mondayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addComponent(tuesdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(wednesdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thursdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fridayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saturdayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sundayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(sleepSubmit)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mondayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayInputActionPerformed

    }//GEN-LAST:event_mondayInputActionPerformed

    private void sleepSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepSubmitActionPerformed
     java.awt.EventQueue.invokeLater(() -> {

        List<JTextField> fields = Arrays.asList(
                mondayInput,
                tuesdayInput,
                wednesdayInput,
                thursdayInput,
                fridayInput,
                saturdayInput,
                sundayInput
        );

        ArrayList<SleepInput> weeklySleep = new ArrayList<>();

        try {
            boolean readBeforeBed = jCheckBox1.isSelected();
            String book = "";
            if(readBeforeBed){
                book = jTextField1.getText().trim();
            }
            
            String reason = jTextField2.getText().trim();
            boolean gotUp = !reason.isEmpty() && !reason.equalsIgnoreCase("Enter why?");
            
            for (JTextField field : fields) {
                int hours = Integer.parseInt(field.getText().trim());
                weeklySleep.add(new SleepInput(hours));
            }

            SleepAnalyzer analyzer = new SleepAnalyzer();
            analyzer.calcAvSleep(weeklySleep);
            
                SleepInput infoForFeedback = weeklySleep.get(0);
                SleepFeedback feedback = new SleepFeedback(analyzer, infoForFeedback);

                JOptionPane.showMessageDialog(this, " Your average sleep is: " + analyzer.getAverageSleep() + " hours"
                +feedback.getFeedback(), "Sleep Feedback", JOptionPane.INFORMATION_MESSAGE
                );

            new HydrationGUI(userName, userAge, userWeight, analyzer).setVisible(true);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter valid numbers only");
            }
        });
   

        
        dispose();
    }//GEN-LAST:event_sleepSubmitActionPerformed

    private void tuesdayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayInputActionPerformed

    private void wednesdayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayInputActionPerformed

    private void thursdayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayInputActionPerformed

    private void fridayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayInputActionPerformed

    private void saturdayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayInputActionPerformed

    private void sundayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayInputActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField fridayInput;
    private javax.swing.JLabel fridayLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mondayInput;
    private javax.swing.JLabel mondayLabel;
    private javax.swing.JTextField saturdayInput;
    private javax.swing.JLabel saturdayLabel;
    private javax.swing.JLabel sleepInfoText;
    private javax.swing.JLabel sleepPageText;
    private javax.swing.JButton sleepSubmit;
    private javax.swing.JTextField sundayInput;
    private javax.swing.JLabel sundayLabel;
    private javax.swing.JTextField thursdayInput;
    private javax.swing.JLabel thursdayLabel;
    private javax.swing.JTextField tuesdayInput;
    private javax.swing.JLabel tuesdayLabel;
    private javax.swing.JTextField wednesdayInput;
    private javax.swing.JLabel wednesdayLabel;
    // End of variables declaration//GEN-END:variables
}
